<html>
<head>
    <!-- declare meta tag -->
    <?php echo $this->getChildHtml('meta');?>
    <?php echo $this->getChildHtml('head');?>
    <!-- end declare -->

    <!-- declare title  tag -->
    <?php echo $this->getChildHtml('z_title');?>
    <!-- end title declare -->

    <!-- declare css links -->
    <?php echo $this->getChildHtml('z_css');?>
    <!-- end css links declare -->

    <!-- declare js links -->
    <?php echo $this->getChildHtml('z_js');?>
    <!-- end js links declare -->

    <!-- declare favicon icon -->
    <?php echo $this->getChildHtml('z_favicon');?>
    <!-- end favicon icon declare -->
</head>
<body>
<section class="header">
    <div class="header">
        <?php echo $this->getChildHtml('header');?>
    </div>
</section>
<div class="container ">
    <div class="col-lg-12 col-xs-12">
        <div class="nav menu">
            <?php echo $this->getChildHtml('menu');?>
        </div>
        <div class="row">
            <section class="midlle">
                <div  class="middle">
                    <div class="col-lef col-lg-3 col-sm-6">
                        <?php
                        echo $this->getChildHtml('left'); ?>
                    </div>
                    <div class="col-lg-6">
                        <?php
                        echo $this->getChildHtml('content');
                        ?>
                    </div>
                    <div class="col-right col-lg-3 col-sm-6">
                        <?php
                        echo $this->getChildHtml('right');
                        ?>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <section class="footer">
        <div class="footer">
            <?php
            echo $this->getChildHtml('footer');
            ?>
        </div>
    </section>
</div>

</body>
</html>