<style>
	label {
		width: 140px;
		line-height: 30px;
	}
	.control-label {
		font-weight: bold;
	}
</style>
<h1>Customer infos</h1>
<form action="<?php echo Mage::getBaseUrl();?>binhnh/index/lala" method="post" id="my_form">
	<label class="control-label" for="name">Name</label>
	<input type="text" name="name" class="form-control required-entry" placeholder="Full name"/><br />
	<label class="control-label" for="email">Email</label>
	<input type="text" name="email" class="form-control required-entry validate-email" placeholder="Email"/><br />
	<label class="control-label" for="address">Address</label>
	<input type="text" name="address" class="form-control required-entry" placeholder="Address"/><br />
	<label class="control-label" for="phone">Phone</label>
	<input type="text" name="phone" class="form-control required-entry validate-phoneLax" placeholder="Phone"/><br />
	<label class="control-label" for="submit">Checkout</label>
	<input type="submit" name="submit" class="btn btn-default button"/>
</form>
<script>
	var myForm = new VarienForm('my_form', true);
</script>